CREATE TABLE "customers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "phone" varchar(15) UNIQUE NOT NULL,
  "address" text,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "products" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "quantity" integer NOT NULL,
  "desc" text,
  "price" integer DEFAULT 0,
  "status" varchar(50) NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);


CREATE TABLE "orders" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "total_quantity" integer NOT NULL,
  "total_amount" float NOT NULL,
  "status" varchar(50) NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now()),
  "customer_id" integer
);

CREATE TABLE "orders_detail" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "order_id" integer,
  "quantity" integer NOT NULL,
  "unit_price" float NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");

ALTER TABLE "orders_detail" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "orders_detail" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

--1 Xem danh sách đơn hàng

Select customers.name as "Tên khách hàng",
customers.email as "Email khách hàng",
customers.phone as "Số điện thoại khách hàng",
orders.total_quantity as "Tổng số lượng sản phẩm",
orders.total_amount as "Tổng tiền đơn hàng",
orders.status as "Trạng thái đơn hàng",
orders.created_at as "Ngày đặt hàng"
From customers
Inner join orders on customers.id = orders.customer_id 

--2 Xem chi tiết đơn hàng

Select customers.name as "Tên khách hàng",
customers.email as "Email khách hàng",
customers.phone as "Số điện thoại khách hàng",
products.name as "Tên sản phẩm",
products.id as "Mã Sản phẩm",
orders_detail.quantity as "Số lượng sản phẩm",
orders_detail.unit_price as "Giá sản phẩm",
orders_detail.quantity * orders_detail.unit_price AS "Tổng tiền từng sản phẩm",
orders.total_quantity as "Tổng số lượng sản phẩm",
orders.total_amount as "Tổng tiền đơn hàng",
orders.status as "Trạng thái đơn hàng",
orders.created_at as "Ngày tạo đơn hàng",
orders.updated_at as "Ngày cập nhật cuối cùng"
From customers
Inner join orders on customers.id = orders.customer_id 
Inner join orders_detail on orders.id = orders_detail.order_id
Inner join products on orders_detail.product_id = products.id
