import "./globals.css";
import { Providers } from "./providers";
import { useLocale } from "next-intl";
import { NextIntlClientProvider } from "next-intl";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const locale = useLocale();

  let messages = (await import(`../../../messages/${locale}.json`)).default;

  return (
    <html lang={locale} className="dark">
      <body>
        <Providers>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
